import Head from "next/head";
import Layout from "@/components/Layout";
import Heading from "@/components/Heading";
import { addProductMutateFn } from "@/lib/tq/products/api";

import ProductForm from '@/components/forms/ProductForm'

export default function AddProduct() {

  return (
    <>
      <Head>
        <title>Commerce App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Heading component={"h1"}>Add Product</Heading>
        <ProductForm submitHandler={addProductMutateFn} />
      </Layout>
    </>
  );
}

// render page at build time on server
export const getStaticProps = async () => {
  return {
    props: {},
  };
};
