import Head from "next/head";
import Image from "next/image";
import Link from "next/link"
import Layout from "@/components/Layout";
import Heading from "@/components/Heading";
import Paragraph from "@/components/Paragraph";
import QueryBoundary from "@/components/QueryBoundary";
import ProductList from "@/components/ProductList";
import { getProductsFromDB } from "@/lib/api-functions/server/products/queries";
import { QueryClient, dehydrate } from "@tanstack/react-query";
import { STORAGE_KEY } from "@/lib/tq/products/settings";
import { Button } from "@/components/mui"
import { useRemoveProduct } from "@/lib/tq/products/mutations";

export default function AdminProductList() {

  const removeMutation = useRemoveProduct();

  const removeHandler = (id) => {
    removeMutation.mutate(id)
  }

  return (
    <>
      <Head>
        <title>Commerce App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Heading component={"h2"}>Products Admin</Heading>
        <Button component={Link} href={`/admin/products/add`}>Add Product</Button>
        <QueryBoundary>
          <ProductList removeHandler={removeHandler}/>
        </QueryBoundary>
      </Layout>
    </>
  );
}

export const getStaticProps = async (context) => {
  const products = await getProductsFromDB().catch((err) => console.log(err));
  const queryClient = new QueryClient();

  await queryClient.setQueryData(
    [STORAGE_KEY],
    JSON.parse(JSON.stringify(products))
  );

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  };
};
