import Head from "next/head";
import Image from "next/image";
import Link from "next/link"
import Layout from "@/components/Layout";
import Heading from "@/components/Heading";
import Paragraph from "@/components/Paragraph";
import QueryBoundary from "@/components/QueryBoundary";
import OrderList from "@/components/OrderList";
import { getOrdersFromDB } from "@/lib/api-functions/server/orders/queries";
import { QueryClient, dehydrate } from "@tanstack/react-query";
import { STORAGE_KEY } from "@/lib/tq/orders/settings";
import { Button } from "@/components/mui"
import { useRemoveOrder } from "@/lib/tq/orders/mutations";

export default function AdminOrderList() {

  const removeMutation = useRemoveOrder();

  const removeHandler = (id) => {
    removeMutation.mutate(id)
  }

  return (
    <>
      <Head>
        <title>Commerce App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Heading component={"h2"}>Orders Admin</Heading>
        <Button component={Link} href={`/admin/Orders/add`}>Add Order</Button>
        <QueryBoundary>
          <OrderList removeHandler={removeHandler}/>
        </QueryBoundary>
      </Layout>
    </>
  );
}

export const getStaticProps = async (context) => {
  const Orders = await getOrdersFromDB().catch((err) => console.log(err));
  const queryClient = new QueryClient();

  await queryClient.setQueryData(
    [STORAGE_KEY],
    JSON.parse(JSON.stringify(Orders))
  );

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  };
};
