import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { QueryClient, dehydrate } from '@tanstack/react-query';
import Layout from '@/components/Layout';
import Heading from '@/components/Heading';
import Paragraph from '@/components/Paragraph';
import QueryBoundary from '@/components/QueryBoundary';
import BasketList from '@/components/BasketList';
import { getBasketsFromDB } from '@/lib/api-functions/server/baskets/queries';
import { STORAGE_KEY } from '@/lib/tq/baskets/settings';
import { Button } from '@/components/mui';
import { useRemoveBasket } from '@/lib/tq/baskets/mutations';

export default function AdminBasketList() {
  const removeMutation = useRemoveBasket();

  const removeHandler = (id) => {
    removeMutation.mutate(id);
  };

  return (
    <>
      <Head>
        <title>Commerce App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Heading component="h2">Baskets Admin</Heading>
        <QueryBoundary>
          <BasketList removeHandler={removeHandler} />
        </QueryBoundary>
      </Layout>
    </>
  );
}

export const getStaticProps = async (context) => {
  const Baskets = await getBasketsFromDB().catch((err) => console.log(err));
  const queryClient = new QueryClient();

  await queryClient.setQueryData(
    [STORAGE_KEY],
    JSON.parse(JSON.stringify(Baskets)),
  );

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  };
};
