import Head from 'next/head';
import Image from "next/image";
import Link from 'next/link';
import Layout from '@/components/Layout';
import Heading from '@/components/Heading';
import { AllPosts } from '@/lib/hygraph/queries';
import {
  Card,
  CardActions,
  CardContent,
  CardMedia,
  List,
  ListItem,
} from '@/components/mui';

const { HYGRAPH_ENDPOINT, HYGRAPH_TOKEN } = process.env;

export default function Blog({ ssd = [] }) {
  console.log(ssd, `ssd`);
  return <>
    <Head>
      <title>Blog</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Layout>
      <Heading>Blog</Heading>
      <List component="ol" sx={{ listStyle: 'none' }}>
        {ssd.map(({ id, title, slug, heroImage: { url } }) => (
          <ListItem key={id}>
            <Card component="article" sx={{ width: '100%' }}>
              <CardMedia sx={{ display: 'grid', placeContent: 'center' }}>
                <Image
                  alt={title}
                  src={url}
                  width={200}
                  height={200}
                  style={{
                    maxWidth: "100%",
                    height: "auto"
                  }} />
              </CardMedia>
              <CardContent>
                <Heading component="h2">{title}</Heading>
              </CardContent>
              <CardActions>
                <Link href={`/blog/${slug}`}>Read more...</Link>
              </CardActions>
            </Card>
          </ListItem>
        ))}
      </List>
    </Layout>
  </>;
}

export const getStaticProps = async () => {
  // make call to hygraph to get blog posts

  const allPosts = await fetch(HYGRAPH_ENDPOINT, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json; charset="UTF8"',
      Authorization: `Bearer ${HYGRAPH_TOKEN}`,
    },
    body: JSON.stringify({
      query: AllPosts,
    }),
  })
    .then((res) => res.json())
    .catch((err) => console.log(`API ERROR:`, err));

  const posts = allPosts.data.blogPosts;

  return {
    props: {
      ssd: posts,
    },
  };
};
