import Head from 'next/head';
// import { Inter } from 'next/font/google'
import Layout from '@/components/Layout';
import Heading from '@/components/Heading';
import ContactForm from '@/components/forms/ContactForm';
import ContactHeader from '@/components/ContactHeader';
import { Box } from '@mui/material';

// const inter = Inter({ subsets: ['latin'] })

export default function Contact() {
  return (
    <>
      <Head>
        <title>Contact Form</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Box component="section">
          <ContactHeader
            title="Contact Us"
            imageSrc={
              'https://images.unsplash.com/photo-1605235456089-289f866adef2?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'
            }
          />
          {/* <Heading>Contact</Heading> */}

          <ContactForm />
        </Box>
      </Layout>
    </>
  );
}
