import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { Button, AccessTimeFilledIcon} from '@/components/mui'
import Layout from '@/components/Layout'
import Heading from '@/components/Heading'
import Paragraph from '@/components/Paragraph'
import QueryBoundary from '@/components/QueryBoundary'
import ProductList from '@/components/ProductList'


export default function Home() {
  return (
    <>
      <Head>
        <title>Commerce App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Heading component={'h2'}>Home Page</Heading>
        <QueryBoundary>
          <ProductList/>
        </QueryBoundary>
      </Layout>
    </>
  )
}


