import Head from 'next/head';
import { withPageAuthRequired } from '@auth0/nextjs-auth0';
import Layout from '@/components/Layout';
import Heading from '@/components/Heading';
import UserDisplay from '@/components/UserDisplay';

export default function Profile({ user }) {
  return (
    <>
      <Head>
        <title>Commerce App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Heading component="h2">Profile Page</Heading>
        <UserDisplay ssd={user} />
      </Layout>
    </>
  );
}

export const getServerSideProps = withPageAuthRequired();
