import Head from 'next/head';
import Image from 'next/image';
import { useContext } from 'react';
import { useUser } from '@auth0/nextjs-auth0/client';
import { Router, useRouter } from 'next/router';
import { Button, AccessTimeFilledIcon } from '@/components/mui';
import Layout from '@/components/Layout';
import Heading from '@/components/Heading';
import { UIContext, UIProvider } from '@/components/contexts/UI.context';
import Paragraph from '@/components/Paragraph';

export default function Profile() {
  const { showMessage } = useContext(UIContext);
  const { user, error, isLoading } = useUser();
  const router = useRouter();

  if (!user) {
    router.push('/api/auth/login');
    return <Paragraph>Redirect to login page</Paragraph>;
  }

  return (
    <>
      <Head>
        <title>Commerce App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Heading component="h2">Profile Page</Heading>
        {/* <Button
          variant="contained"
          onClick={() =>
            showMessage({
              type: 'error',
              string: 'test message',
            })
          }
        >
          Alert
        </Button> */}
        (// eslint-disable-next-line @next/next/no-html-link-for-pages)
        <a href="/api/auth/login">Login</a>
      </Layout>
    </>
  );
}
