import Head from "next/head";
import Image from "next/image";
import Link from "next/link"
import Layout from "@/components/Layout";
import Heading from "@/components/Heading";
import Paragraph from "@/components/Paragraph";
import QueryBoundary from "@/components/QueryBoundary";
import ProductList from "@/components/ProductList";
import { getProductsFromDB } from "@/lib/api-functions/server/products/queries";
import { QueryClient, dehydrate } from "@tanstack/react-query";
import { STORAGE_KEY } from "@/lib/tq/products/settings";
import { Button } from "@/components/mui"

export default function AddProduct() {

  return (
    <>
      <Head>
        <title>Commerce App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Heading component={"h1"}>Add Product</Heading>
        <p>Form goes here</p>
      </Layout>
    </>
  );
}

export const getStaticProps = async (context) => {
  return {
    props: {},
  };
};
